# Generated by Django 4.2.1 on 2023-05-27 19:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Blog", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bloguser",
            name="image",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
